### ISSUE TITLE
Explicit HTTP method, always

### ISSUE THREAD

**Issue by jmagnusson** [ducaale/xh#143]
First off - thanks for making this incredible tool!

One thing that bothers me slightly with curl and httpie is the choice of an implicit GET argument. I just think the time saved by not having to type GET and an extra space is not worth the more clear distinction made regarding the choice of HTTP method.

What are your thoughts on this? Would you be open to always requiring the argument?

**Comment by blyxxyz** [comment]
That's a valid concern. I'm usually a fan of boring, explicit APIs. If software tries to guess what you mean then you have to guess what the software thinks you mean.

But I think that for now we want xh to be useful as a drop-in replacement for HTTPie, warts and all. That automatically rules out a change like this, because it'd break a lot of commands.

And there's implicit behavior beyond guessing the HTTP method:
- It tries to read stdin as the request body if it's not a terminal.
- Request items (form fields, headers, etc.) use a concise syntax that's [hairy to parse](https://github.com/ducaale/xh/blob/14e8223bb1bc2a25aef60d17539fce272146b420/src/request_items.rs#L35) and [tricky to enhance without breaking compatibility](https://github.com/ducaale/xh/issues/3).
- Request data is by default assumed to be JSON.
- The URL scheme is by default assumed to be `http://` if it's missing.
- When downloading, an output filename is guessed by default. Predicting it is not trivial, it can depend on both the URL and the response.
- The output is different depending on whether the response is piped or going to a terminal.

I think this is fine if you're running the tool directly. If I entered the command myself and I'm watching it as it runs then I'll soon notice if it's doing something I didn't expect, and I can just adjust the command, no harm done. Meanwhile I get to save a few keypresses, which does add up.

But it means I would personally not use xh/HTTPie in a script. If I write it once and it runs a thousand times then predictability is more vital, fixing it is harder, and a few extra keypresses don't matter.

I think that's an ok tradeoff to make.

**Comment by jmagnusson** [comment]
Thank you @blyxxyz for spending time to write down your thoughts on this. I understand your line of reasoning and I think that it's good that you all agree on the project's direction (judging by the thumb's up from @ducaale I guess that's the case).
